### ISSUE TITLE
Data types in the models have changed causing errors

### ISSUE THREAD

**Issue by airwoflgh** [NodeJSmith/otf-api#61]
**Describe the bug**

Because the data model of MemberDetail has changed, validation of the data types now fails for the get_workout_data.py example

liability changed from None -> bool
createdBy changed from str -> None
memberReferrer changed from str -> a new JSON object with one attribute

**To Reproduce**

1. Set username / password environment variables.
2. Run the example code from https://otf-api.readthedocs.io/en/stable/usage/#Get-Workout-Data
3. See error

**Expected behavior**

Output of workout data

**Proposed Fix**

In src/otf_api/models/member_detail.py, add the following class before MemberDetail:

```
class MemberReferrer(OtfItemBase):
    member_referrer_uuid: str = Field(..., alias="memberReferrerUUId")
```

And change the following attributes in the MemberDetail class to:

```
    liability: bool
    created_by: None = Field(..., alias="createdBy")
    member_referrer: MemberReferrer = Field(..., alias="memberReferrer")
```

**Error log**

Ignore the inconsistent line numbers in get_workout_data.py comapred with what is in the example. I added 9 lines to allow for command line input of username and password on the command line if environment variables are blank.

```
Traceback (most recent call last):
  File "get_workout_data.py", line 202, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "get_workout_data.py", line 21, in main
    otf = otf = Otf(USERNAME, PASSWORD)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/otf_api/api.py", line 84, in __init__
    self.member = self._get_member_details_sync()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/otf_api/api.py", line 98, in _get_member_details_sync
    return models.MemberDetail(**resp.json()["data"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for MemberDetail
liability
  Input should be None [type=none_required, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.7/v/none_required
createdBy
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
memberReferrer
  Input should be None [type=none_required, input_value={'memberReferrerUUId': '6...4b01-be5c-3f99c126121b'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/none_required
Exception ignored in: <function Otf.__del__ at 0x108708180>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/otf_api/api.py", line 122, in __del__
  File "/usr/local/lib/python3.11/site-packages/otf_api/api.py", line 117, in session
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 298, in __init__
RuntimeError: no running event loop
```

**Desktop (please complete the following information):**
 - OS: OSX 13.7
 - Python: 3.11 (installed from homebrew)

**Comment by NodeJSmith** [comment]
@airwoflgh  Sorry, didn't mean to close this without response - can you try the newest version (v0.8.1) and let me know if that works for you?

FWIW, the data models haven't changed, it's just that Orange Theory is incredibly inconsistent with what data is included and I can only validate with the data I receive back with my own account, which doesn't have the member referrer, for example. So there will be more of these issues cropping up as more people use the package - I'm going to be trying to make some of the fields more flexible by allowing None/Any on ones I don't know about, so at least things won't break.

**Comment by airwoflgh** [comment]
Thanks - no problem. Will give the latest version ago tonight.

I hear you - one of the reasons I dislike APIs as a lot of developers will build one without a DTD or a complete Swagger type interface / documentation due to either being not for public consumption or simply being lazy.

It has been helpful - appreciate you putting this together.

**Comment by airwoflgh** [comment]
All good - thank you!
